asr_additional_kwargs: {}
asr_additional_kwargs: {}
asr_beam_size: 5
asr_ctc_weight: 0.1
asr_device: null
asr_lm_weight: 0.2
asr_maxlenratio: 1.0
asr_nbest: 1
vad_device: null
vad_min_duration_off: 0.5
vad_min_duration_on: 0.0
merge_segments: false
